name: concretecomeback-www
region: nyc
static_sites:
- name: web
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: lookgugu/concretecomeback.com
  build_command: npm run build
  output_dir: dist
  index_document: index.html
  error_document: 404.html
domains:
- domain: concretecomeback.com
  type: PRIMARY
- domain: www.concretecomeback.com
  type: ALIAS
alerts:
- rule: DEPLOYMENT_FAILED
